/*
 * EditCategoryForm.java
 *
 * Created on March 12, 2006, 5:01 AM
 */

package net.bruncle.notebook;

import java.awt.event.*;
/**
 *
 * @author  Jeremy
 */
public class EditCategoryForm extends javax.swing.JPanel implements ActionListener{
    
    /** Creates new form EditCategoryForm */
    public EditCategoryForm() {
        initComponents();
        addDetail();
        setPreferredSize(new java.awt.Dimension(400, 300));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        lblTitle = new javax.swing.JLabel();
        scrCategories = new javax.swing.JScrollPane();
        lstCategories = new javax.swing.JList();
        lblCatTitle = new javax.swing.JLabel();
        txtCatTitle = new javax.swing.JTextField();
        btnAddEdit = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Verdana", 0, 18));
        lblTitle.setText("Edit categories:");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        scrCategories.setViewportView(lstCategories);

        add(scrCategories, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 290, 150));

        lblCatTitle.setFont(new java.awt.Font("Verdana", 0, 12));
        lblCatTitle.setText("Title:");
        add(lblCatTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        add(txtCatTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 90, -1));

        btnAddEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnAddEdit.setFont(new java.awt.Font("Verdana", 0, 14));
        btnAddEdit.setText("Add/Edit");
        btnAddEdit.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddEdit.setContentAreaFilled(false);
        btnAddEdit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAddEdit.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAddEdit.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(btnAddEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 70, -1));

        btnDel.setBackground(new java.awt.Color(255, 255, 255));
        btnDel.setFont(new java.awt.Font("Verdana", 0, 14));
        btnDel.setText("Delete");
        btnDel.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDel.setContentAreaFilled(false);
        btnDel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnDel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 50, -1));

    }//GEN-END:initComponents
    
    /**
    *  Fine tunes the GUI - adds data which cannot be added to the previous method due to dynamic regeneration
    */
    public void addDetail(){
	 lstCategories.setListData(getCategoryData());
	 MouseListener mouseListener = new MouseAdapter() {
	     public void mouseClicked(MouseEvent e) {
	         if (e.getClickCount() == 2) {
	             int index = lstCategories.locationToIndex(e.getPoint());
	             txtCatTitle.setText(getCategoryData()[index]);
	          }
	     }
	 };
	 lstCategories.addMouseListener(mouseListener);
	 
	 btnAddEdit.addActionListener(this);
	 btnDel.addActionListener(this);
    }
    
    /**
    *  A list of the titles of all of the categories in this notebook
    */
    public String[] getCategoryData(){
    	String[] catTitles = new String[Main.getInstance().getCategories().size()];
    	int i = 0;
    	for (Category cat : Main.getInstance().getCategories()){
    		catTitles[i++] = cat.getTitle();
    	}
    	return catTitles;
    }
    
    /**
    *  Called when a gui event occurs, eg. a user clicks a button
    *  @see  java.awt.event.ActionListener
    */
    public void actionPerformed(ActionEvent e){
    	if (e.getSource() == btnDel){
    		if (Main.getInstance().getGUI().isConfirmed("Are you sure you want to delete this category? You will lose all the notes associated with it..."))
    			if (Main.getInstance().getGUI().isConfirmed("Are you sure you're sure? You can't ever get them back...")){
    				Main.getInstance().getCategories().remove(lstCategories.getSelectedIndex());
    				Main.getInstance().saveData();
    				lstCategories.setListData(getCategoryData());
    			}
    	}
    	else if (e.getSource() == btnAddEdit){
    		if (lstCategories.getSelectedIndex() != -1)
    			Main.getInstance().getCategories().get(lstCategories.getSelectedIndex()).setTitle(txtCatTitle.getText());
    		else
    			Main.getInstance().getCategories().add(new Category(txtCatTitle.getText()));
    		Main.getInstance().saveData();
    		lstCategories.setListData(getCategoryData());
    		txtCatTitle.setText("");
    	}
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEdit;
    private javax.swing.JButton btnDel;
    private javax.swing.JLabel lblCatTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList lstCategories;
    private javax.swing.JScrollPane scrCategories;
    private javax.swing.JTextField txtCatTitle;
    // End of variables declaration//GEN-END:variables
    
}
